### ISSUE TITLE
Actividades Sergio

### ISSUE THREAD

**Issue by NeilyGuerra** [NeilyGuerra/Pract10#3]
1.- determinar si un numero es primo o no. 
2. realizar una funcion que permita realizar el factorial. 
3. dado un numero en segundos, devolver cuantas horas y minutos representa, el numero se le pedirá al usuario. 
4. devolver si un numero es de la suerte o no . 
5. calcular la longitud de un nombre. 
6. devolver el numero de ocurrencias de una letrra que se pedira la usuario

**Comment by SergioAC52** [comment]
hecho 1. es primo o no

**Comment by SergioAC52** [comment]
hecho 2. factorial

**Comment by SergioAC52** [comment]
hecho 5.  calcular la longitud de un nombre

**Comment by SergioAC52** [comment]
Hecho 6. ocurrencias de una letra

**Comment by SergioAC52** [comment]
Merges hechos
